# Generated by Django 4.2 on 2023-04-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_cod', models.IntegerField(unique=True, verbose_name='ПИН')),
                ('title', models.CharField(max_length=155, verbose_name='Название магазина')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('В ожидании', 'В ожидании'), ('На складе', 'На складе'), ('Отменен', 'Отменен')], default=('Новый', 'Новый'), max_length=20, verbose_name='Статус заказа')),
                ('warehouse', models.CharField(max_length=155, verbose_name='Склад')),
            ],
        ),
    ]
